services:
  front:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    user: 1000:1000
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    command: /bin/bash
    environment:
      NODE_ENV: development
